=== AnkurS11/Maintenance_and_Support/DOM Parser/Documents.xsd
<?xml version="1.0" encoding="UTF-8"?>
<pms:schema xmlns:pms="http://www.w3.org/2001/XMLSchema">
   <pms:element name="PMS" type="Support" />
   <pms:complexType name="Support">
      <pms:sequence>
         <pms:element name="Documents" type="Doc1" minOccurs="1" maxOccurs="unbounded" />
      </pms:sequence>
   </pms:complexType>
   
   <pms:complexType name="Doc1">
      <pms:sequence>
         <pms:element name="Team_ID" type="pms:string" />
         <pms:element name="Title" type="pms:string" />
         <pms:element name="Date" type="pms:date" />
         <pms:element name="Author" type="pms:string" />
         <pms:element name="Pages" type="pms:integer" />
      </pms:sequence>
      <pms:attribute name="Doc_no" type="pms:ID" use="required" />
   </pms:complexType>
   <pms:simpleType name="set_value">
      <pms:restriction base="pms:integer">
         <pms:minInclusive value="0" />
         <pms:maxInclusive value="4" />
      </pms:restriction>
   </pms:simpleType>
   <pms:simpleType name="set_status">
      <pms:restriction base="pms:string">
         <pms:enumeration value="In Progress" />
         <pms:enumeration value="On Hold" />
         <pms:enumeration value="Resolved" />
         <pms:enumeration value="Cancled" />
      </pms:restriction>
   </pms:simpleType>
   <pms:simpleType name="set_loc">
      <pms:restriction base="pms:string">
         <pms:enumeration value="Offsite" />
         <pms:enumeration value="Onsite" />
      </pms:restriction>
   </pms:simpleType>
   
</pms:schema>

=== AnkurS11/Maintenance_and_Support/DOM Parser/XML_Documents.xml
<?xml version="1.0" encoding="UTF-8"?>
<PMS xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="Documents.xsd">
  
  <Documents Doc_no="Doc001">
    <Team_ID>TM01</Team_ID>
    <Title>Login</Title>
    <Date>2010-01-13</Date>
    <Author>Ankur</Author>
    <Pages>4</Pages>
  </Documents>
  <Documents Doc_no="Doc002">
    <Team_ID>TM04</Team_ID>
    <Title>Connections</Title>
    <Date>2013-04-11</Date>
    <Author>Pradeep</Author>
    <Pages>6</Pages>
  </Documents>
  <Documents Doc_no="Doc003">
    <Team_ID>TM03</Team_ID>
    <Title>Change password</Title>
    <Date>2010-02-04</Date>
    <Author>Priyanka</Author>
    <Pages>2</Pages>
  </Documents>
  <Documents Doc_no="Doc004">
    <Team_ID>TM01</Team_ID>
    <Title>Testing</Title>
    <Date>2010-06-28</Date>
    <Author>Adarsh</Author>
    <Pages>9</Pages>
  </Documents>
  <Documents Doc_no="Doc005">
    <Team_ID>TM03</Team_ID>
    <Title>Configuration</Title>
    <Date>2009-11-13</Date>
    <Author>Ayushree</Author>
    <Pages>6</Pages>
  </Documents>
  <Documents Doc_no="Doc006">
    <Team_ID>TM02</Team_ID>
    <Title>Add User</Title>
    <Date>2009-08-18</Date>
    <Author>Jeetank</Author>
    <Pages>2</Pages>
  </Documents>
  <Documents Doc_no="Doc007">
    <Team_ID>TM05</Team_ID>
    <Title>Remove User</Title>
    <Date>2009-08-22</Date>
    <Author>Jeetank</Author>
    <Pages>3</Pages>
  </Documents>
  <Documents Doc_no="Doc008">
    <Team_ID>TM01</Team_ID>
    <Title>Email Sync</Title>
    <Date>2019-09-19</Date>
    <Author>Amber</Author>
    <Pages>3</Pages>
  </Documents>
  
</PMS>
